"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authController_1 = require("../controllers/authController");
const authRouter = (0, express_1.Router)();
authRouter.post("/signup", authController_1.userSignupController);
authRouter.post("/login", authController_1.userLoginController);
authRouter.get("/logout", authController_1.userLogoutController);
authRouter.get("/google", authController_1.googleAuthController);
authRouter.get("/google/callback", authController_1.googleAuthCallback);
exports.default = authRouter;
